import { spawn, spawnSync, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseProjectConfig } from '@mcpgen/config-schema';
import { generateProject } from '@mcpgen/generator';
import { parseOpenApi } from '@mcpgen/openapi-adapter';
import { afterEach, describe, expect, it } from 'vitest';
import { startFixtureApi, type FixtureApiHandle } from '../../src/fixture-api.js';

const CONFIG_PATH = fileURLToPath(new URL('../../../../fixtures/openapi-3.1/customer.mcp.config.json', import.meta.url));
const SPEC_PATH = fileURLToPath(new URL('../../../../fixtures/openapi-3.1/customer.json', import.meta.url));
const API_KEY = 'sk-generated-package-sentinel';

let outputDir: string | undefined;
let api: FixtureApiHandle | undefined;
let child: ChildProcessWithoutNullStreams | undefined;

afterEach(async () => {
  child?.kill();
  child = undefined;
  await api?.stop();
  api = undefined;
  if (outputDir) await rm(outputDir, { recursive: true, force: true });
  outputDir = undefined;
});

async function generateThePoProject(): Promise<string> {
  const spec = JSON.parse(await readFile(SPEC_PATH, 'utf8'));
  const parsed = await parseOpenApi(spec, { sourceId: 'customer-oas31' });
  if (!parsed.value) throw new Error(`fixture spec failed to parse: ${JSON.stringify(parsed.diagnostics)}`);
  const operations = Object.fromEntries(parsed.value.operations.map((op) => [op.id, op]));

  const configRaw = JSON.parse(await readFile(CONFIG_PATH, 'utf8'));
  const configResult = parseProjectConfig(configRaw);
  if (!configResult.value) throw new Error(`fixture config failed to parse: ${JSON.stringify(configResult.diagnostics)}`);

  outputDir = await mkdtemp(join(tmpdir(), 'mcpgen-e2e-generated-'));
  const result = await generateProject({ config: configResult.value, operations }, outputDir);
  if (result.diagnostics.length > 0) throw new Error(`generation failed: ${JSON.stringify(result.diagnostics)}`);
  return outputDir;
}

/**
 * The definitive proof for self-contained mode (TIP §29/§30): a package
 * generated by THIS session, `npm install`ed in complete isolation from the
 * monorepo's own node_modules, must run standalone. This is not a build
 * check — it is the actual generated dist/cli.mjs, spawned as a real
 * subprocess, over real stdio, against a real HTTP fixture API.
 */
describe('generated package — runs standalone, fully isolated from the monorepo (P2-W15-E01/E02)', () => {
  it('npm installs cleanly with only real, published dependencies', async () => {
    const dir = await generateThePoProject();
    const pkg = JSON.parse(await readFile(join(dir, 'package.json'), 'utf8'));
    expect(Object.keys(pkg.dependencies).every((name: string) => !name.startsWith('@mcpgen'))).toBe(true);

    const install = spawnSync('npm', ['install', '--no-audit', '--no-fund'], { cwd: dir, encoding: 'utf8' });
    expect(install.status, install.stderr).toBe(0);
  }, 30_000);

  it('the bundle contains zero references to any unpublished @mcpgen package', async () => {
    const dir = await generateThePoProject();
    const bundle = await readFile(join(dir, 'dist/cli.mjs'), 'utf8');
    expect(bundle).not.toContain('@mcpgen');
  });

  it('serves all three P0 tools and executes get_customer against the real fixture API', async () => {
    const dir = await generateThePoProject();
    spawnSync('npm', ['install', '--no-audit', '--no-fund'], { cwd: dir });

    api = await startFixtureApi({ expectedToken: API_KEY });
    child = spawn(process.execPath, ['dist/cli.mjs', 'serve'], {
      cwd: dir,
      env: { CUSTOMER_API_URL: api.baseUrl, CUSTOMER_API_KEY: API_KEY },
    });

    const response = await new Promise<Record<string, unknown>>((resolve, reject) => {
      const timer = setTimeout(() => reject(new Error('timed out waiting for a response')), 10_000);
      let buffer = '';
      child!.stdout.on('data', (chunk: Buffer) => {
        buffer += chunk.toString('utf8');
        const newlineIndex = buffer.indexOf('\n');
        if (newlineIndex !== -1) {
          clearTimeout(timer);
          resolve(JSON.parse(buffer.slice(0, newlineIndex)));
        }
      });
      setTimeout(() => {
        child!.stdin.write(
          `${JSON.stringify({
            jsonrpc: '2.0',
            id: 1,
            method: 'tools/call',
            params: {
              name: 'get_customer',
              arguments: { customer_id: 'c-42' },
              _meta: {
                'io.modelcontextprotocol/protocolVersion': '2026-07-28',
                'io.modelcontextprotocol/clientInfo': { name: 'e2e-generated', version: '1.0' },
                'io.modelcontextprotocol/clientCapabilities': {},
              },
            },
          })}\n`,
        );
      }, 300);
    });

    const result = response.result as { isError?: boolean; structuredContent?: unknown };
    expect(result.isError).toBeFalsy();
    expect(result.structuredContent).toMatchObject({ id: 'c-42' });

    const request = api.requests.at(-1)!;
    expect(request.headers.authorization).toBe(`Bearer ${API_KEY}`);
  }, 30_000);

  it('fails fast with zero stdout bytes when a required secret is missing — BR-009 holds for generated packages too', async () => {
    const dir = await generateThePoProject();
    spawnSync('npm', ['install', '--no-audit', '--no-fund'], { cwd: dir });

    const result = await new Promise<{ exitCode: number | null; stdout: string; stderr: string }>((resolve) => {
      const proc = spawn(process.execPath, ['dist/cli.mjs', 'serve'], { cwd: dir, env: {} });
      let stdout = '';
      let stderr = '';
      proc.stdout.on('data', (c: Buffer) => (stdout += c.toString('utf8')));
      proc.stderr.on('data', (c: Buffer) => (stderr += c.toString('utf8')));
      proc.on('close', (exitCode) => resolve({ exitCode, stdout, stderr }));
    });

    expect(result.exitCode).not.toBe(0);
    expect(result.stdout).toBe('');
    expect(result.stderr).toContain('CUSTOMER_API_URL');
  }, 30_000);
});
